[package]
name = "ristretto-bulletproofs"
version = "0.1.0"
authors = ["Cathie <cathie@chain.com>"]

[dependencies]
curve25519-dalek = { version = "^0.15", features = ["nightly"] }
sha2 = "^0.7"
rand = "^0.4"

[features]
yolocrypto = ["curve25519-dalek/yolocrypto"]
std = ["curve25519-dalek/std"]