[package]
name = "ristretto-bp"
version = "0.1.0"
authors = ["Cathie <cathie@chain.com>"]

[dependencies]
#curve25519-dalek = "^0.14"
curve25519-dalek = { git = "https://github.com/dalek-cryptography/curve25519-dalek", branch = "develop", features = ["nightly"]}
sha2 = "^0.7"
rand = "^0.4"